.github/actions/build-to-release-branch/action.yml, .github/workflows/release.yml
This PR introduces a GitHub action to build generated assets into the `release` branch every time code is merge to `main`. It assumes that `release` branch commits will be tagged for release via Composer or else included in other projects as a submodule.
This is the history of the release branch when using this action, as [tested earlier today in this repository](https://github.com/wikimedia/shiro-wordpress-theme/actions):
```
*   eede1a3e (HEAD -> release, origin/release) Build to 'release' from main#5b2685f8
|\  
| * 5b2685f8 (origin/main, main) Bump build
| * 8e976671 Use shorter ref name, full disambiguation not needed
* | 1672b027 Build to 'release' from main#d75887a1
|\| 
| * d75887a1 Remove test code
* | 91cafb02 Build to 'release' from main#6aede1f4
|\| 
| * 6aede1f4 Change …
```
=> Introduce release action

.gitignore, composer.json, composer.lock
It may be necessary for the Wikimedia sites to consume this theme as a composer dependency and not a submodule, so this PR adds a `composer.json`. This is required to install the theme via composer, even from a VCS source (that is, not using Packagist).
=> Add theme composer.json

.github/workflows/php.yml, composer.json, composer.lock, functions.php, phpcs.xml, template-parts/header/page-single.php, template-parts/modules/cards/card-horizontal.php, template-parts/modules/cards/card-vertical.php, template-parts/modules/featured/posts.php, template-parts/modules/list/item.php, template-parts/modules/related/posts.php
Now that we have PHP linting wired up, some PRs will trigger an onslaught of PHPCS errors. This PR preemptively addresses  errors in the code touched by #4 so that the feature PR can be addressed independently.
It also resolves a global issue with #7 where outdated versions of the WP standards were being used which could cause fatal errors when running `phpcs` in the GitHub action.
=> Address PHPCS errors in files touched by #4

.github/actions/build-to-release-branch/action.yml, .github/workflows/release-develop.yml, README.md
To be able to test preproduction changes without merging to `main`, this PR introduces a separate `develop` and corresponding `release-develop` branch.
=> Introduce a Develop branch and release-develop build

inc/editor/namespace.php
Permits blocks from [`wikimedia/vegalite-wordpress-plugin`](wikimedia/vegalite-wordpress-plugin) to be rendered in Shiro
=> Support vegalite plugin

composer.json, inc/editor/blocks/double-heading.php, phpcs.xml, sidebar-list.php, template-parts/profiles/role-item.php
Several PHP warnings have been reported in the deployed environment, which began to show up after the upgrade to PHP 8 (at which point the undefined array key became a warning). This PR addresses several pervasive warnings, and fixing them will make it easier to recognize true issues in the application health logs.
=> Address PHP warnings observed in VIP logs

composer.json, composer.lock
PHP 8 environments cause a fatal error when running wpcs PHPCS sniffs:
```
PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /Users/akshitsethi/wp-local-docker-sites/snowsoftware-test/wordpress/wp-content/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
```
[There is a fix for this](https://github.com/WordPress/WordPress-Coding-Standards/commit/7cd46bed1e6a7a2af3fe24c7f4a044da3076d8f4) but it hasn't yet been released for the official repo. Unfortunately it's not as simple as pointing our `composer.json` at the branch containing this updated code because wpcs is a dependency of several of _our_ dependencies, and composer will choke when asked to resolve two different version specifications.
This uses …
=> Dynamically patch phpcs to fix vsprint exception

inc/editor/namespace.php
A simple mu-plugin can serve as the compatibility layer for Shiro and other blocks on a per-site basis, rather than requiring every plugin to be known to the theme. This permits site-specific mu-plugins to handle integration.
=> Make Shiro allowed blocks filterable rather than coupling list to theme releases

inc/template-functions.php, template-parts/modules/images/credit.php
- Whitespace fixes (executed using `phpcbf` to auto-correct)
- Add comments for function parameters
- Use wp_parse_query instead of inconsistent parse_query
- Adjust ignore comments for query performance to match new PHPCS syntax
- Rename one function which was improperly namespaced
=> 530: PHPCS changes for PR #16

inc/editor/namespace.php
In retrospect, before this goes live, we should avoid introducing a new filter for specifying allowed blocks when we can simply add a higher-priority filter function on core's same `allowed_block_types_all` hook.
=> 762: Do not add our own custom filter when we can use core's

inc/taxonomy-content-language.php
When creating content locally with the latest version of shiro theme, any attempts to update newly-created posts break with the following error:
Fatal error: Uncaught Error: Call to undefined function wp_create_term()
in /srv/www/wikimediafoundation/public_html/wp-content/themes/shiro/inc/taxonomy-content-language.php on line 80
This is happening because in the REST API endpoint hit to update content in the block editor, wp-admin/includes/taxonomy.php isn't loaded by default. This change ensures that this file is required whenever trying to update language taxonomy terms.
=> Fix language tax update when saving content in the block editor

assets/src/editor/blocks/card/index.js, assets/src/sass/blocks/_card.scss, assets/src/sass/components/_group.scss, assets/src/sass/editor/_global.scss, assets/src/sass/helpers/_style-guide-variables-overrides.scss, assets/src/sass/style.scss, assets/src/sass/utilities/_theme-supports.scss, inc/editor/namespace.php
This is part of ticket [758 - Adding Colors](https://app.zenhub.com/workspaces/wikimedia-foundation-602350f5e5f555000e33e28c/issues/gh/humanmade/wikimedia/758) 
**Back**
**Front**
=> 758 - Contrast link

assets/src/scripts/block-collapsible-text.js
This script is throwing warnings on every build. Adding an explicit return should fix it.
=> [hotfix] Fix eslint warning in collapsible-block js handler

assets/src/sass/objects/_header.scss, single-profile.php, template-parts/header/profile-single.php
This change allows for multiple member profile team tags to display as comma-separated list of links in the front-end. Single tags display next to the role title and are also outputted as a link.
_Multiple tags:_
_Single tag:_
For issue https://github.com/humanmade/wikimedia/issues/787.
=> 787: Staff Profile Tagging

assets/src/editor/hooks/useMeta.js, assets/src/editor/plugins/hide-page-title-controls/index.js, assets/src/sass/objects/_header.scss, functions.php, inc/post-types/page.php
Adds a toggle control on the page status box, which toggles whether the page title will be displayed or visually hidden.
=> [#767]: Add "hide page title" control

assets/src/sass/components/_nav-search.scss, assets/src/sass/components/_primary-nav.scss, assets/src/sass/components/_searchform.scss, template-parts/site-header/wrapper.php, template-parts/site-navigation/search.php, template-parts/site-navigation/wrapper.php
This PR intends to move the search field to the header.
https://github.com/humanmade/Wikimedia/issues/764
**NOTE: Search box is hidden when viewport width is <= 1023 px.**
=> [#764] Move the search field to the header

inc/assets.php
Webpack Helpers now uses "development-asset-manifest.json" as the default filename for an asset manifest in dev mode, but the theme was still looking for the old "asset-manifest.json". This change makes it possible to develop frontend assets using `npm run start:webpack:theme`.
This isn't the whole solution for #779, but I've attached it to that issue because this is a prerequisite for being able to even use the dev server at all.
=> Fix asset manifest filename reference for dev server

assets/src/editor/plugins/hide-page-title-controls/index.js
Fixes an error which shows up in the post-new.php screen for any post types other than pages.
The "wmf_hide_title" value issn't registered for any post types other than Pages, so trying to access it with the `useMeta` hook was throwing errors for any users who weren't super-admins. This moves the hook inside a component which is conditionally rendered, so that it isn't being accessed where it shouldn't be.
=> [#767] Prevent error accessing unregistered meta value

assets/src/sass/content/_content.scss, assets/src/sass/content/_search-results.scss, functions.php, inc/editor/blocks/blog-post.php, inc/search.php, search.php
This pull request intends to improve search results page.
https://github.com/humanmade/Wikimedia/issues/763
=> [#763] Improvements for search results page

inc/taxonomy-content-language.php
This PR intends to add a filter to ensure that  posts having different `current-language` taxonomy are not displayed on the post listings.
https://github.com/humanmade/Wikimedia/issues/797
In order to allow creating content in languages that don't have a dedicated site, we register "Content Language" as a taxonomy which can be set on a per-post basis. This allows for individual posts relevant to communities not otherwise served by the blog to be translated and associated with the original post in the same way that MultiLingual Press handles associating content between different language sites.
If a translation post is created and the taxonomy `content-language` is set to a language different than the main language term, currently set to `en_US`.
I decided to add a filter to remove from …
=> #797: Fix for content language taxonomy filter

functions.php, inc/assets.php, inc/editor/namespace.php
This allows assets to be drawn from different manifests depending on what is available. That way it is possible to use the live-reloading dev server while developing blocks alongside previously-built static theme assets, or vice versa, where previously there was no way to load some prod assets while the dev server was running.
This makes the `npm run start:webpack:theme` and `npm run start:webpack:editor` aliases work as expected.
=> 779: Permit assets to be loaded from first available manifest

inc/editor/namespace.php
This PR intends to fix a problem on Block Editor list item.
I found that sinceWordPress 6.1 list items has their own blocks, so I needed to add `core/list-item` to the list of allowed blocks to fix the issue.
=> #805: Fix Block Editor list item issue after WordPress upgrade

assets/src/scripts/modules/donate-buttons.js
`URLSearchParams#toString` does not include the leading `?`, so we need to add it back in otherwise this search-replace breaks the href of the link.
For humanmade/wikimedia#834
=> 834: Prefix search params with ? when updating donate button

inc/classes/customizer/class-base.php
This PR intends to fix and improve the page selection on Customizer.
- Removed the limit of 100 pages, as Wikimedia currently has more than 150 pages. 
I found it very hard finding the pages, full of duplication, so I decided to:
- Sort it alphabetically
- Remove pages with empty title from the list
- Display only published pages
- Add page ID (to give user the capacity of looking for page ID if needed)
- Add page relative URL (as many pages has the same title)
=> #825: Fix and improve Customizer page selection interface

functions.php, inc/breadcrumb-links.php, page-block-editor.php
This PR intends to add a custom setting on page edit controls to allow more control over page breadcrumb links.
- Add "Breadcrumb Links" settings section on page editor
- Allow user to show or hide breadcrumbs for particular pages
- Allow user to set default breadcrumb link text
- Allow user to set default breadcrumb link url
- Edit a page
- Change parameters on "Breadcrumb Link" section
- View the page and see it reflected
https://github.com/humanmade/Wikimedia/issues/819
=> #819: Improve control over page breadcrumb links

assets/src/sass/blocks/_accordion.scss, assets/src/scripts/block-accordion.js
I tried to solve this with scroll-padding-top, but because the FAQ item is hidden in an overflow container, that rule doesn't seem to take effect. The easiest way to handle this situation is to detect a targeted anchor on page load, and open the container / scroll it into view using JS.
=> 845: Open and anchor to the selected FAQ item on page load

assets/src/editor/blocks/table-of-contents/deprecations.js, assets/src/editor/blocks/table-of-contents/index.js, assets/src/sass/blocks/_table-of-contents.scss, assets/src/scripts/modules/toc-nav.js, functions.php, inc/editor/blocks/linked-toc-item.php, inc/editor/blocks/toc.php
<details>
<summary>RFC on this approach, originally included in the description here</summary>
I've baked this down to the reduced POC of my idea to get a direction check from @goldenapples, @MiguelAxcar and possibly @joeleenk. The ticket humanmade/wikimedia#814 wants to be able to support third-level items, and while working on the ticket, I began to explore moving the rendering of the block to the server wholesale. This could decouple the block from a strict hierarchy (which Greg has noted is error prone, in a comment on the original ticket, e.g. you can't use the ToC block within a reusable block) — at the expense of codifying some rules such as "there must only be one on a page."
The way this branch works is,
- Build a list of heading blocks while rendering the post's blocks
- …
=> 814: Server-render TOC block for third-level items

page-block-editor.php, template-parts/header/header-content.php
An unexpected behaviour was found on the breadcrumb link feature, already pushed to production.
The problem is reported by Greg here:
https://github.com/humanmade/Wikimedia/issues/819#issuecomment-1552170329
As I'm in the end of my allocation to Wikimedia, I'm pushing this draft pull request that potentially address the issues, still with some additional tests neede.
I also addressed a problem that I found: if a page wasn't yet edited with the metabox "_Breadcrumb link_" on it, the value of the metadata `show_breadcrumb_links` will be empty instead of `off`, and my code considering the value as `off`, not displaying the breadcrumb. That is making the breadcrumb links to disappear on all the Wikimedia's block pages until someone edit the page and set the config "_Show Breadcrumb Link_" to …
=> #819: Breadcrumb links for classic editor pages

inc/editor/blocks/toc.php
This PR intends to add a production quickfix to disable displaying H3 on TOC block.
=> #873: Quickfix to disable adding H3 to TOC

template-parts/profiles/role-list.php
This PR intends to fix iterating problems on profiles page.
The code was prepared to display a single executive instead of a list, but it does not match the component used to select executives which is a list of checkboxes, so I fix it to display a list, keeping the same layout.
=> #875: Bugfix profiles page

functions.php, inc/security.php
This PR intends to add additional security headers, addressing problems reported by a scan done by `securityheaders.com` on `soundlogo.wikimedia.org`.
- Strict-Transport-Security: Makes browsers to use only HTTPS for communicate, it improve security of data send.
- Content-Security-Policy: It defines sources approved of content that browser can load, it help prevent attacks of Cross-Site Scripting (XSS) and other data injection.
- X-Content-Type-Options: It stop browsers of MIME-sniffing and make it use the declared content-type, reduce risk of drive-by downloads.
- Referrer-Policy: Control how much referrer information (sent via the Referer header) is include with requests, offer control of privacy and data leakage.
- Permissions-Policy: Allow website to specify which browser features …
=> 788: Add additional security headers

inc/security.php
Adds YouTube and Vimeo domains to the allowed frame sources as specified in the content security policy.
=> #885: Add "frame-src" directives to Content-Security-Policy header

assets/src/editor/blocks/home-page-hero/style.scss
Enables scrolling inside the container which holds the rotating headings in the home-hero block's edit component, so that it's possible to see (and edit) the text if more headings are set than can fit in the block.
Also adds a fade-out at the bottom of the headings wrapper to indicate that there's more content that can be scrolled into view.
This code is available on the develop site. If you edit the home page at https://wikimediafoundation-org-develop.go-vip.co/wp-admin/post.php?post=10&action=edit and add additional headings to the hero block they should all be visible.
=> #891: Allow scrolling to view all rotating headers in home hero block

README.md, package-lock.json, package.json
@varnent I spun this up earlier, it will let us make a few of the changes you wanted from the reverted commit without any build impact.
Regarding any Dependabot or `npm audit` security issues: They are all in dependencies of our build process, so none of the specific issues I saw in the report are actual threat surfaces for the theme because we do not run any public-facing node processes (the distribution version of the theme has no dependency code and only includes the built versions of the theme-specific source). See this article for more details, we're squarely in the situation described: https://overreacted.io/npm-audit-broken-by-design/
We can address any such errors when and if we update the supported node version of the build system, and we absolutely aim for a clean bill of health …
=> Update some npm dependencies and clarify install process in README

assets/src/scripts/post-list-filters.js
The filters we introduced in #55 work well, but the code that manages them still runs on pages outside the News section. Because the filter interface doesn't exist on other pages, these `querySelector` calls returned `null`, and attempts to manipulate those null values fail.
This PR slightly refactors the existing code to add guards around the node queries so that we only run code when the corresponding HTML's on the page.
Fixes #88.
**Testing Instructions**
Visit any page other than the News section. No error resembling `TypeError: Cannot read properties of null (reading 'addEventListener')` should appear.
=> 88: Fix JS error blocking execution of unrelated plugin code.

assets/src/sass/content/_search-results.scss, assets/src/scripts/search-results-dropdown.js, assets/src/scripts/shiro.js, inc/search.php, inc/template-functions.php, search.php, template-parts/pagination.php
- Added sort dropdown with mobile responsiveness and positioning adjustments, follow other buttons and tabs design/colors
- Introduced `search-results-dropdown.js` to support dropdown functionality for search results, adding toggle functionality and making click outside of the dropdown to hide the dropdown
- Modified the search sorting mechanism to accept custom sort options from query parameters.
- It now supports ordering by relevance, date in both ascending and descending orders.
- Search for anything on the site
- Check the sort dropdown's appearance and responsiveness
- Test dropdown toggle functionality
- Verify sorting works by relevance, date (newest first), and date (oldest first)
- Ensure that external clicks hide the dropdown
=> #886: Modify search results to add sorting options buttons

inc/editor/blocks/toc.php
This PR intends to push a fix for error which are flooding the PHP logs. 
It still needs testing.
```
PHP message: Warning: DOMDocument::loadHTML(): Tag path invalid in Entity, line: 125 in /var/www/wp-content/themes/shiro/inc/editor/blocks/toc.php on line 37 [wikimediafoundation-org-develop.go-vip.co/about/annualreport/] [wp-content/themes/shiro/inc/editor/blocks/toc.php:37 DOMDocument->loadHTML(), wp-content/themes/shiro/inc/editor/blocks/toc.php:152 WMF\Editor\Blocks\TOC\get_headings_from_post_content(), wp-includes/class-wp-hook.php:312 WMF\Editor\Blocks\TOC\render_toc_block(), wp-includes/plugin.php:205 WP_Hook->apply_filters(), wp-includes/class-wp-block.php:293 apply_filters('render_block'), wp-includes/class-wp-block.php:244 WP_Block->render(), wp-includes/class-wp-block.php:244 …
```
=> Fix: Supress error messages flooding the PHP logs

.github/workflows/php.yml, .github/workflows/release-develop.yml, .github/workflows/release.yml
Bumps build action dependencies to latest versions, and sets build to validate in PHP 8.1 to ensure VIP environment compatibility.
=> Upgrade dependency action references in GitHub Action pipelines

single-profile.php, single-story.php, template-parts/header/profile-single.php
This PR addresses one fatal and three warnings observed in the application runtime logs while upgrading the Foundation site to PHP 8.1.
```
2023-11-08T18:11:16.880587639Z PHP message: Warning: Undefined array key "link" in /var/www/wp-content/themes/shiro/single-profile.php on line 90 [wikimediafoundation.org/profile/selena-deckelmann/] [wp-includes/template-loader.php:106 include('wp-content/themes/shiro/single-profile.php'), wp-blog-header.php:19 require_once('wp-includes/template-loader.php'), index.php:17 require('wp-blog-header.php')]
2023-11-08T18:11:44.203293989Z PHP message: Warning: Undefined variable $parent_link in /var/www/wp-content/themes/shiro/single-story.php on line 34 [wikimediafoundation.org/story/translations-and-copyright/] [wp-includes/template-loader.php:106 …
```
=> 916: Resolve PHP warnings and errors observed during 8.1 upgrade

single-profile.php, template-parts/header/profile-single.php
Resolves error when passing WP_Error to `esc_url`, by asserting value is a string before rendering link.
```
Uncaught TypeError: ltrim(): Argument #1 ($string) must be of type string, WP_Error given
```
See humanmade/wikimedia#916
=> 916: Fix subsequent PHP fatal when trying to cast WP_Error to string

template-parts/page/page-stories.php
Resolves PHP fatal,
```
PHP message: Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /var/www/wp-content/themes/shiro/template-parts/page/page-stories.php:18
```
See humanmade/wikimedia#916
=> 916: Fix PHP fatal: Guard against string values of rand_translation

template-parts/modules/list/list.php, template-parts/page/page-profiles.php, template-parts/page/page-related.php
For humanmade/wikimedia#916
In my local, this resolves all remaining issues with the Stories and Annual Reports pages, and introduces a similar guard in other templates that have not been observed to be a problem.
We could consider refactoring this to a `get_template_args_from_meta` that applies the empty-check internally, but for now, this patch should resolve the production issues.
=> 916: Fix PHP fatal: Consistently guard against empty-string template-args

home.php, template-parts/post-list-filters.php
Fixes humanmade/wikimedia#833: News section did not have margin on small viewports
- Incorrect closing tag in filter interface, which caused browser to prematurely terminate the <main> tag
- Adds a wrapper class to the blog-list component on the homepage template to ensure it gets the consistent mobile margin
=> Fix News page margin on narrow viewports

404.php, comments.php, footer.php, front-page.php, functions.php, header.php, home.php, index.php, page-block-editor.php, page-data.php, page-freeform.php, page-landing.php, page-list.php, page-report-landing.php, page-report-section.php, page-report.php, page.php, search.php, sidebar.php, single-story.php, single.php, taxonomy-role.php
VIP runtime logs reveal that some requests are made directly to theme files, which is possibly benign but also possibly as a penetration testing tactic. The file will not load if WordPress is not running, because `get_header()` will not be defined, but this guard code ensures that the page exits immediately if any top-level theme file is accessed.
Fixes humanmade/wikimedia#920
=> 920: Guard against direct file access

inc/security.php
This PR focuses on updating the Content Security Policy (CSP) to allow exceptions crucial for Jetpack, Matomo analytics and WordPress Admin Backend. These exceptions are necessary to ensure full functionality of these tools while maintaining the security standards of our site.
Modifications to the CSP settings in `inc/security.php` are implemented to support scripts, frames, styles, images, fonts, and connection endpoints from trusted external sources related to Jetpack, Matomo, and essential admin features.
The `set_content_security_policy()` function has been updated with the following exceptions:
- Script Source: https://s0.wp.com added for Jetpack scripts
- Frame Source: https://widgets.wp.com included for Jetpack widgets
- Style Source: Expanded with https://s0.wp.com and Matomo …
=> #925: Update to Content Security Policy (CSP) to fix issues on Jetpack, Matomo and WordPress Admin

assets/src/sass/components/_embed-youtube.scss, assets/src/sass/style.scss
This PR addresses the issue where the YouTube video embed block was not dynamically adjusting to the format of the embedded video, causing the video thumbnails to be cropped. The modification ensures that the video embed block and the player adapt seamlessly to the screen size and the video format, providing an optimal viewing experience without cropping or visual discrepancies. 
I set the minimum width of 321 px to the videos, to ensures that YouTube does not default to a low-quality thumbnail.
Feature was tested on these platforms / clients:
- Navigate to the ["Knowledge is Human" page (on develop)](https://wikimediafoundation-org-develop.go-vip.co/our-work/knowledge-is-human/)
- Scroll down to the "Wikimedia: Supporting free knowledge" section.
- Observe the video embed block under …
=> #924: Fix embed YouTube video so the video and thumbnail remains responsive on multiple viewport sizes

inc/security.php
This needs testing, but this theme must delegate the CSP header generation to the new security plugin when that plugin is present and active.
=> Wikimedia-900: Delegate header generation to security plugin when present

inc/template-functions.php
This PR intends to add a hotfix which was breaking role pages on `develop`.
Example of role page:
https://wikimediafoundation-org-develop.go-vip.co/role/board/
Error being thrown:
```
PHP message: PHP Fatal error: Uncaught TypeError: Illegal offset type in /var/www/wp-content/themes/shiro/inc/template-functions.php:99
```
I already deployed this hotfix to Shiro's `develop`, and updated WMF `develop`, fixing the issue, assuring that the fix was effective.
=> Hotfix: PHP Fatal on inc/template-functions.php line 99

.github/workflows/php.yml
Several of our steps in the PHPCS GitHub action assume that we're running in a PR context. We should be linting all files when running outside of a PR, and should only try to report errors outside the runner when _in_ a PR context.
This may require merging to `main` to test, because of how GitHub Actions work.
For #111
=> Shiro 111: Iterate on PHP code quality action to execute outside of PR context

inc/template-functions.php
A PHP Fatal error was encountered on the Roles listing page. To immediately mitigate this, a provisional fix was introduced in PR [#129](https://github.com/wikimedia/shiro-wordpress-theme/pull/129).
It was needed to trace the root cause of this error, as it may reveal broader systemic issues within our codebase. 
After deploying the fix code, the error log provided us some important info, so logging the error is no longer necessary.
Details added to error log
```
Term ID 990: Invalid parent ID of [0].
Term ID 16: Invalid parent ID of [0].
Term ID 9: Invalid parent ID of [0].
Term ID 10: Invalid parent ID of [0].
```
So, the guard of checking `if ( is_int( $parent ) && $parent > 0 ) {` is enough for the case.
=> Remove error log debug info

assets/src/editor/blocks/profile-list/index.js, assets/src/editor/blocks/profile/index.js, assets/src/editor/components/post-control.js, composer.lock
Follow-on from #130 (and subsequent commits to `main`) to get us the latest and greatest, and also test that actions are running properly on PRs.
Also includes a guard associated with humanmade/wikimedia#927
=> Update dev dependencies and guard against missing PostControl

sidebar-list.php, single-profile.php
This PR is part of our ongoing effort to maintain clean and efficient logs by addressing and resolving specific PHP warning messages, as keeping the log free of not so important warnings is crucial for efficient debugging and monitoring, ensuring that we can quickly identify and address more significant issues when they arise.
1. **sidebar-list.php**:
- Refined the definition of `$item_text` to default to an empty string if neither 'title' nor 'name' keys are set in `$list_section`, addressing the warning: `PHP Warning: Undefined array key "name" in sidebar-list.php on line 61`.
2. **single-profile.php**:
- Add lines to set default values for `$link['link']` and `$link['title']` if not present in the `$share_links` array, addressing multiple warnings of the form: `PHP Warning: Undefined …
=> [WIP] Fix PHP warning fixes

inc/fields.php
This PR removes a legacy code which was preventing the Field Manager fields to be available when editing posts when the post has blocks. 
This fixes the issue were Field Manager fields were missing when editing profiles.
=> WMF #956: Remove logic to make Field Manager fields to load only when content has no blocks

inc/template-functions.php
We had an unusual situation on WIKI-954 where the profile of Stephen LaPorte, the Foundation's current General Counsel, was not showing up in the list of profiles with the 'executive' role. Stephen's profile had the correct 'executive' role term associated, and was properly published, but his profile's ID was not returned in the results of the WP_Query from the `wmf_get_role_posts()` function.
I identified that ordering by meta_value causes WP_Query to generate a SQL query which _excludes_ any records which do not have the specified meta key set. This is actually tracked as a long-standing WP Core bug:
https://core.trac.wordpress.org/ticket/19653
The quickest solution to the problem is to remove the `orderby` entirely, and sort the array in-memory within PHP before returning the query …
=> 954: Avoid meta sort in profile query to ensure all records are returned

assets/src/editor/blocks/banner/index.js, assets/src/editor/blocks/home-page-hero/edit.js, assets/src/editor/blocks/home-page-hero/index.js
This change removes the homepage hero `srcset` attribute from the image by removing the `imageId` attribute from the `ImagePicker` component. This prevents the component from generating the `wp-image-{ID}` class needed for WP to automatically generate the `srcset` and `sizes` attributes.
This will allow editors to force the banner to always display the same image regardless of screen size or device in order to prevent blurry images in Chrome.
**Testing Instructions:**
1. Navigate to the demo page here: https://wikimediafoundation-org-develop.go-vip.co/
2. Check that the homepage hero image does not include the `wp-image-{ID}` and that the `srcset` and `sizes` attributes are missing.
=> Remove the Homepage Hero srcset Attribute

template-parts/header/header-content.php
This allows other parts of the site to choose to disable the template-side page title if they provide it in post content
=> Report plugin integration: Permit page title suppression

assets/src/editor/blocks/accordion-item/index.js
This causes the dreaded "This block contains unexpected or invalid content." notice, but clicking "attempt recovery" fixes the issue. I attempted to write a block deprecation but it was not successfully detected/applied, we may need to revisit this to clean up the warnings in a future sprint. Both versions of the block render and function correctly after this change.
=> Annual Report: Permit custom classnames in Accordion Item block

assets/src/scripts/block-accordion.js
Scope JS query for accordion items to Shiro's version of the block only. This prevents bad interaction with other accordions on page.
=> No-conflict accordions with the WMF Reports version

template-parts/modules/images/credit.php
Allows in-house-created images without Wikimedia Commons information to be omitted from list, used for functional icons
=> Skip photos without any credit info when rendering photo credits

single-profile.php
For humanmade/wikimedia#909: A warning was output every time we tried to access data off of a malformed link record.
PHP message: Warning: Undefined array key "link" in /var/www/wp-content/themes/shiro/single-profile.php
This error originates in bad content (a contact link with a name but no corresponding link URL), but we should guard against that to avoid broken links and resolve this error.
=> 909: Do not output profile link if link data has no URL

inc/template-tags.php
Some posts have references to invalid author IDs, which breaks CAP author lookup. If author cannot be found, skip byline.
(Accidentally fixed this while estimating how to resolve the CAP bug where it throws an error if a boolean (false) is passed in as the user record value.)
Fixes humanmade/wikimedia#910
=> #910: Only call coauthors links if author is available

assets/src/editor/components/cta/index.js
This change fixes the bug where the URL icon for editing the CTA link in the Card block was not showing up on focus.
For https://github.com/humanmade/Wikimedia/issues/894.
=> 894: URL Editor Icon Does Not Display for Card Block

assets/src/editor/blocks/carousel/block.json, assets/src/editor/blocks/carousel/index.js, assets/src/sass/blocks/_carousel.scss
This change adds Carousel block loop (rewind) functionality and fixes the default pagination styling and the autoplay functionality which was enabled by default regardless of user settings.
For https://github.com/humanmade/Wikimedia/issues/422.
=> 422: Add Carousel Block Loop (Rewind) Functionality

inc/fields/profile.php, inc/template-functions.php, template-parts/profiles/role-list.php
The key change here is to `usort` all profiles by `last_name` meta value (which has already been coopted for sorting purposes), but importantly to treat a missing value as `z` instead of `''`. Maryana Iskander's profile already had the `last_name` key `1Iskander`, but this wasn't displaying first because (a) that section wasn't named in a way that it triggered any of the hard-coded logic in the template, and (b) Margo Lee had _no_ `last_name` set and an empty string apparently comes before `'1'` when PHP compares by `strnatcasecmp`.
To control sort order on the staff page:
1. Make sure the "Sort Name" (formerly "last name") metabox on each employee profile is filled out with values that will sort correctly, numbers before letters and letters in alphabetical order.
2. Make sure the …
=> #1020: Fix profile ordering on staff page and support manual role ordering

inc/template-functions.php
One function within our object generation was not using the same comparator as the others, so sub-role profile ordering was not going through the same natural comparison function used elsewhere.
Fixes final bug identified while verifying WIKI-1020 on Production, see [this comment on #1020](https://github.com/humanmade/Wikimedia/issues/1020#issuecomment-2253135281)
=> #1020: Consistently sort by last_name throughout roles pages

.svgrrc, assets/src/editor/blocks/banner/index.js, assets/src/editor/blocks/card/index.js, assets/src/editor/blocks/contact/index.js, assets/src/editor/blocks/double-heading/index.js, assets/src/editor/blocks/external-link/index.js, assets/src/editor/blocks/landing-page-hero/index.js, assets/src/editor/blocks/linked-toc-columns/index.js, assets/src/editor/blocks/mailchimp-subscribe/index.js, assets/src/editor/blocks/share-article/index.js, assets/src/editor/blocks/spotlight/index.js, assets/src/editor/blocks/stairs/index.js, assets/src/editor/blocks/table-of-contents/deprecations.js, assets/src/editor/blocks/toc-columns/index.js, assets/src/editor/blocks/tweet-this/index.js, functions.php
SVG loading became broken throughout the application after #156 due to a mismatch in how `wp-scripts`' bundled [@svgr/webpack](https://www.npmjs.com/package/@svgr/webpack) configuration differed from the prior configuration within Shiro. The primary purpose of this PR is to fix that by doing the following
- Add an SVGR configuration file [per this documentation](https://react-svgr.com/docs/configuration-files/) to set [`icon` mode](https://react-svgr.com/docs/options/#icon) for parity with the prior build, and to configured SVGO to not remove the `viewBox` attribute ([see this SO thread](https://stackoverflow.com/a/76120573))
- Change all `import SvgComponent from './path/to/icon.svg'` statements to `import { ReactComponent as SvgComponent } ...`
It also resolves an unrelated issue with …
=> 1037/1012 [followup]: Fix hero description tag, fix SVG loading

inc/editor/blocks/linked-toc-item.php
If the post ID property is present but invalid or if no permalink could be found for it, the prior logic would clear out the `href` and cause that item to link back to the current page.
This patch adjusts the link parsing logic to verify the post ID is numeric before trying to look up an href, and also only updates the content with the new href if a permalink URL was correctly found.
Go to a page like https://wikimedia.vipdev.lndo.site/about/annualreport/2022-annual-report/pillar1/ and hover over each link in the table of contents. They should all point to a valid and correct URL, _e.g._ "Donors" should never point to the `/pillar1/` page itself.
=> 1021: Fix linked ToC link item redirection issue

package-lock.json, package.json
`npm audit fix` got most of them, but also needed to update to latest WP-Scripts package. Only breaking change was a stylelint configuration change which has no practical impact on our system. 
v29 actually may fix some of the hot-reloading behavior; testing will tell later. Current priority is consistency of build and minimizing GH security warnings.
Testing: Node CI should pass, build should succeed.
=> Dependencies: Update to wp-scripts v30 to fix high-severity NPM Audit warnings

assets/src/sass/base/_base.scss
Two final changes
Before | After
----- | -----
Before | After
----- | -----
=> 1017 alignment followup

inc/editor/blocks/blog-list.php, inc/editor/blocks/blog-post.php
Blog List block should display wide-width in posts.
Screenshots **after**:
=> 1017: Ensure embedded Blog List blocks render as wide-width in posts

.editorconfig, assets/src/editor/blocks/banner/block.json, assets/src/editor/blocks/banner/index.js, assets/src/editor/components/cta/index.js, assets/src/editor/components/url-picker/index.js
Addresses a remaining piece of feedback around the banner block after WIKI-1037, that the CTA should be able to open in a new tab without manually editing the markup saved in the post.
Adds an `openInNewTab` attribute to the banner block, and passes it through to the CTA, which exposes a control in the sidebar:
Since the banner block has many styles and this section may be off-screen and require scrolling, I've also introduced a toolbar button to make it more obvious:
In action:
=> WIKI-1037: Allow opening banner block CTA in new tab

assets/src/editor/blocks/card/index.js
I've based this branch on 1037-banner-block-new-tab to apply the same logic to it.
=> WIKI-1022: Cards Block: Enable the option to choose whether a URL opens in a new tab.

README.md
This repository's build structure deviates a little from the process used in the actual web applications, so we should include a guide to the key branches in the readme.
=> Clarify branch purposes

single.php, template-parts/header/page-single.php
This fixes an error I missed in #175 where we were still calling the old namespace render method.
=> 1010: Render share article block properly in template code

assets/src/editor/blocks/share-article/render.php, assets/src/sass/blocks/_share-article.scss
Per request from Sara. The editor experience will reflect the new dropdown, but only FB and Twitter will be shown on the frontend and they will show in the classic style.
=> Temporarily revert new dropdown Share button to old non-dropdown style

assets/src/editor/blocks/share-article/render.php, assets/src/sass/blocks/_share-article.scss
@pamprn09 Per @sacmp ,
> I recommend not rolling out the share button yet, as I need more time to test its potential impact on the other social media buttons on the website.
We therefore added in these styles and PHP to re-enable the old button method; This reverts commit 8d50dea9649b4255893e2c6e56365f36f9f13b18.
Now that the other version has been deployed, we can proceed with merging this through to preprod.
=> 1010: Re-enable dropdown-style share button

assets/src/sass/helpers/mixins/_mixins-links.scss
I didn't initially realize that some of the categories exist / we might be able to keep some existing category slugs and rename them. This PR is to align the new styles with what the slugs end up being.
https://github.com/humanmade/Wikimedia/issues/1117
=> 1117: UX Refresh - Update category slug classes for styles

assets/src/sass/base/_forms.scss, assets/src/sass/blocks/_table-of-contents.scss
https://github.com/humanmade/Wikimedia/issues/1136
Fixes problems where the buttons styles were overlapping with the select dropdown styles for the:
- ["Sort by" selector on the search page](https://wikimediafoundation-org-develop.go-vip.co/?s=sound+logo)
- [Annual report home page selector](https://wikimediafoundation-org-develop.go-vip.co/about/annualreport/)
- [Report page template for the table of contents selector on mobile](https://wikimediafoundation-org-develop.go-vip.co/about/transparency/2019-2/requests-for-user-information/)
=> 1136: Fix select and button styles overlap

assets/src/editor/blocks/interactive-card/block.json, assets/src/editor/blocks/interactive-card/edit.js, assets/src/editor/blocks/interactive-card/helpers.js, assets/src/editor/blocks/interactive-card/index.js, assets/src/editor/blocks/interactive-card/save.js, assets/src/editor/blocks/interactive-card/style.scss, inc/editor/namespace.php, package-lock.json, package.json, patterns/interactive-cards.php
This change adds the Contributions card CTA section.
We introduce a new block called Interactive Card that makes the bulk of this change. There is also a new block pattern named Interactive Cards that includes the content for the "Contributions section" in the design mockups.
The cards animate on focus and hover except on devices with no pointer device, or when a user selects "reduce motion" within their OS accessibility settings where the cards display all content by default.
**Todo:**
- Preliminary tests show that on tap the cards opens up, but it follows the link immediately after.
- We might need to display the card as expanded on touch devices.
=> 1113: Add Contributions Section

assets/src/sass/helpers/mixins/_mixins-buttons.scss, assets/src/sass/utilities/_theme-supports.scss
This change updates the reverse color palette class rules to add rules for all the colors in order to prevent a nested group block from overwriting another child group block with a color background that was not previously accounted for.
=> Update Reverse Color Palette Class Rules

assets/src/sass/utilities/_theme-supports.scss
@ajvillegas I haven't tested this in practice, but I'm opening it as a proposal for reducing duplication in #223
=> Consolidate loops used to set accessibility color contrast overrides

inc/editor/blocks/mailchimp-subscribe.php
https://github.com/humanmade/Wikimedia/issues/1152
It turns out that the Mailchimp JS is needed, either due to a plugin update or the addition of the checkbox to the form. This restores the JS enqueue.
=> 1152: Enable the Mailchimp JS to fix spam flag

functions.php
https://github.com/humanmade/Wikimedia/issues/1112
Adds direction-rtl class using the same method that RTL styles are applied, so that we can target the selector even when `is_rtl` is false.
=> 1112: Filter body class - add direction-rtl class
